### ISSUE TITLE
question about testing data

### ISSUE THREAD

**Issue by Yufengevan** [China-LiuXiaopeng/BraTS-DMFNet#6]
In your paper,you mentioned that you use zero pad to increase the dimension from 155 to 160 in testing phase. Where is the code about this operation?
Thank you for your reply

**Comment by China-LiuXiaopeng** [comment]
In experiments/DMFNet_GDL_all.yaml defines the operation of "test_transform -> Pad((0, 0, 0, 5, 0))". It will call the "data/transforms.py/Pad()" function to pad the dimension of depth.
